### PR TITLE
Removed the unnecessary phrase "delivered by an"

### PR DESCRIPTION
**Pull request by HarvestingClouds**
Removed the unnecessary phrase "delivered by an" under "Bash/WSL" feature points.

### CODE REVIEW

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[commandline/WSL/about.md](https://github.com/HarvestingClouds/CommandLine-Documentation/blob/patch-2/commandline/WSL/about.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C3%5C5ef5d453-6fc9-df30-73f0-2cf3b60c84c3%5CPullRequest%5C201704032301337697-90%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tommai78101** [comment]
Ha! The previous 2 PRs are all about this.

**Comment by HarvestingClouds** [comment]
@tommai78101 my original PR#88, the first one failed in build step. That's why I opened this one. I hope somebody takes notice soon.

**Comment by bitcrazed** [comment]
Thanks for the fix - already fixed by another user (the errors were caused by an infrastructure issue and are now resolved :))

**Pull request closed without merging**
