### PR TITLE
Add section about using symbolic link (symlink).

### PR DESCRIPTION
**Pull request by EricGT**
Give an example of why you want to use a symbolic link and show how to create the symbolic.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C17%5C5ef5d453-6fc9-df30-73f0-2cf3b60c84c3%5CPullRequest%5C201701170148079262-85%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jackchammons** [comment]
I like the idea of having a section on symlinks. Could you make this more tool agnostic though? Make it a more general example that does not reference a specific utility.

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C26%5C5ef5d453-6fc9-df30-73f0-2cf3b60c84c3%5CPullRequest%5C201701261925327383-85%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jackchammons** [comment]
Looks great @EricGT. Unfortunately I am unable to merge the changes in since you have closed the pull request. Reopen it and I'd be happy to merge this in.

**Comment by EricGT** [comment]
@jackchammons 

Sorry for the problems. I tried to do this as a quick and dirty using the Internet interface, and closed the first one to start a second new one from scratch.  

I am unable to re-open this request `https://github.com/Microsoft/CommandLine-Documentation/pull/85` as it reads `EricGT wants to merge 2 commits into Microsoft:live from unknown repository`.

However for `https://github.com/Microsoft/CommandLine-Documentation/pull/86` it reads `EricGT wants to merge 1 commit into Microsoft:live from EricGT:live`. This one looks open and ready.

Notice the differences `pull/85` and `pull/86`.

If there are still have problems, I won't mind if you just add something of your own or copy what I have. I am more interested in people learning about WSL and having WSL gain in usage than who wrote what for the FAQ. :)

**Comment by jackchammons** [comment]
Ok, I'll incorporated the changes on my end. Thank you again for your help.

**Pull request closed without merging**
