### PR TITLE
Legal updates from CELA

### PR DESCRIPTION
**Pull request by Taojunshen**
CELA has provided replacement licence files which include separate licenses for CC and code snippets. The Content Engineering Team has been tasked with replacing the license files on all existing repos. The changes to the README file must be at the top of the file to be recognized by license scanners.
 
Please see this communication for more details: [Legal Update Notice](https://microsoft.sharepoint.com/teams/STBCSI/e/CE/_layouts/15/guestaccess.aspx?guestaccesstoken=m4R%2fQ5Es3YlfV%2fUTJ09pb8x50MXjJNNO20%2b9YHpi5%2bo%3d&docid=2_0a46b1b0a931049e5afab07102ab5c0df&rev=11)
 
Please accept the PR as soon as possible.

### CODE REVIEW

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LICENSE](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/LICENSE) | :white_check_mark:Succeeded | |
[LICENSE-CODE](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/LICENSE-CODE) | :white_check_mark:Succeeded | |
[README.md](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/README.md) | :white_check_mark:Succeeded | |
[ThirdPartyNotices](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/ThirdPartyNotices) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C21%5C5ef5d453-6fc9-df30-73f0-2cf3b60c84c3%5CPullRequest%5C201703211845427651-87%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[LICENSE](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/LICENSE) | :white_check_mark:Succeeded | |
[LICENSE-CODE](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/LICENSE-CODE) | :white_check_mark:Succeeded | |
[README.md](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/README.md) | :white_check_mark:Succeeded | |
[ThirdPartyNotices](https://github.com/Taojunshen/CommandLine-Documentation/blob/CELA-updates/ThirdPartyNotices) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C21%5C5ef5d453-6fc9-df30-73f0-2cf3b60c84c3%5CPullRequest%5C201703211857090281-87%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-anpasi** [comment]
Hello,

Please review and merge these updates from CELA.

@bitcrazed, and @EricGT, please redirect me to a more appropriate point of contact if needed.

Cheers,
Andrew Pasic

**Comment by EricGT** [comment]
@v-anpasi I don't know how I was put onto your list. I do not work for Microsoft, therefore I can not help.

**Pull request merged**
